apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-api
  namespace: devops-challenge
  labels:
    app: hello-world-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello-world-api
  template:
    metadata:
      labels:
        app: hello-world-api
    spec:
      containers:
        - name: hello-world-api
          image: ebleman/hello-world-api:2025.01.05-a26c4ad
          ports:
            - containerPort: 3000
