apiVersion: v1
kind: Service
metadata:
  name: hello-world-service
  namespace: devops-challenge
spec:
  selector:
    app: hello-world-api
  type: NodePort
  ports:
    - protocol: TCP
      port: 3000       # Porta interna do cluster
      targetPort: 3000 # Porta do container
      nodePort: 30080  # Porta externa do nó (range: 30000–32767)
