name: Build/Push and Deploy

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
  workflow_run:
    workflows: ["Auto Release Tag"]
    types:
      - completed

jobs:
  build-and-push-and-deploy:
    name: Build/Push and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Iniciar Minikube
        uses: medyagh/setup-minikube@master

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set version and commit SHA
        id: version
        run: |
          if [ "${{ github.event_name }}" == "pull_request" ]; then
            echo "VERSION=pr-${{ github.event.pull_request.number }}" >> $GITHUB_ENV
          else
            echo "VERSION=$(date +'%Y.%m.%d')" >> $GITHUB_ENV
          fi
          echo "COMMIT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Build and Push Docker image
        run: |
          eval $(minikube docker-env)
          cd hello-world-api
          docker build -t ${{ secrets.DOCKER_USERNAME }}/hello-world-api:${{ env.VERSION }}-${{ env.COMMIT_SHA }} .

      - name: Configurar kubectl
        run: |
          kubectl config use-context minikube

      - name: Aplicar Namespace
        run: kubectl apply -f k8s/namespace.yaml

      - name: Aplicar Deployment
        run: kubectl apply -f k8s/deployment.yaml

      - name: Aplicar Service
        run: kubectl apply -f k8s/service.yaml

      - name: Atualizar Imagem do Deployment
        run: |
          kubectl set image deployment/hello-world-api hello-world-api=${{ secrets.DOCKER_USERNAME }}/hello-world-api:${{ env.VERSION }}-${{ env.COMMIT_SHA }} -n devops-challenge