name: CI/CD Docker Build and Tag

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout do código
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Login no Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 3. Definir a versão (para PRs ou Push)
      - name: Set version and commit SHA
        id: version
        run: |
          if [ "${{ github.event_name }}" == "pull_request" ]; then
            echo "VERSION=pr-${{ github.event.pull_request.number }}" >> $GITHUB_ENV
          else
            echo "VERSION=$(date +'%Y.%m.%d')" >> $GITHUB_ENV
          fi
          echo "COMMIT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      # 4. Build da imagem Docker
      - name: Build and Push Docker image
        run: |
          cd hello-world-api
          docker build -t ${{ secrets.DOCKER_USERNAME }}/hello-world-api:${{ env.VERSION }}-${{ env.COMMIT_SHA }} .
          docker push ${{ secrets.DOCKER_USERNAME }}/hello-world-api:${{ env.VERSION }}-${{ env.COMMIT_SHA }}

      # Passo 5: Aplicar arquivos Kubernetes para deploy no cluster
      - name: Set up kubectl
        uses: azure/setup-kubectl@v1

      - name: Deploy to Kubernetes
        run: |
          kubectl set image deployment/hello-world-api hello-world-api=ebleman/hello-world-api:${{ env.VERSION }}-${{ env.COMMIT_SHA }} -n devops-challenge
          kubectl rollout status deployment/my-app
