name: Auto Release Tag

on:
  schedule:
    - cron: "15 13 * * 1-4" # 10:15 BRT (Brasil) = 13:15 UTC, de segunda a quinta
  workflow_dispatch: # Permite execução manual

jobs:
  create-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Garante que pegamos todas as tags

      - name: Obter a última tag
        run: |
          last_tag=$(git describe --tags --abbrev=0 || echo "0.00.00")
          echo "Última tag encontrada: $last_tag"
          echo "tag=$last_tag" >> $GITHUB_ENV

      - name: Calcular nova versão
        run: |
          IFS='.' read -r -a parts <<< "$tag"
          major=${parts[0]}
          minor=${parts[1]}
          patch=${parts[2]}

          if [[ $patch -lt 99 ]]; then
            patch=$((patch + 1))
          else
            patch=1  # Reinicia o patch em 01
            minor=$((minor + 1))  # Incrementa o minor
          fi

          patch=$(printf "%02d" "$patch")  # Formata para dois dígitos

          new_tag="$major.$minor.$patch"
          echo "new_tag=$new_tag" >> $GITHUB_ENV
          echo "Nova versão gerada: $new_tag"


      - name: Criar nova tag e release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git tag ${{ env.new_tag }}
          git push origin ${{ env.new_tag }}
          gh release create ${{ env.new_tag }} --title "Release ${{ env.new_tag }}" --notes "Release automática gerada pelo GitHub Actions."
