name: Auto Release Tag

on:
  schedule:
    - cron: "5 13 * * 1-4" # 10:15 BRT (Brasil) = 13:15 UTC, de segunda a quinta
  workflow_dispatch: # Permite execução manual

jobs:
  create-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Garante que pegamos todas as tags

      - name: Obter a última tag
        run: |
          git fetch --tags  # Garante que pega as tags mais recentes do repositório
          last_tag=$(git tag --sort=-v:refname | head -n 1)
          last_tag=${last_tag:-"0.00.00"}  # Se não houver tags, usa "0.00.00"
          
          echo "Última tag encontrada: $last_tag"
          echo "tag=$last_tag" >> $GITHUB_ENV

      - name: Calcular nova versão
        run: |
          IFS='.' read -r -a parts <<< "$tag"
          major=${parts[0]}
          minor=${parts[1]}
          patch=${parts[2]}

          # Ignorar caracteres não numéricos no patch (extrair apenas a parte numérica)
          patch_number=$(echo "$patch" | sed 's/[^0-9]*//g')

          # Verifica se o valor de patch_number é numérico
          if ! [[ "$patch_number" =~ ^[0-9]+$ ]]; then
            patch_number=0  # Se não for numérico, tratamos como 0
          fi

          # Lógica de incremento
          if [[ $patch_number -lt 99 ]]; then
            patch_number=$((patch_number + 1))
          else
            patch_number=01  # Mantém o formato correto
            minor=$((minor + 1))
          fi

          # Usar printf para garantir que o patch tenha dois dígitos
          patch=$(printf "%02d" "$patch_number")

          new_tag="$major.$minor.$patch"
          echo "new_tag=$new_tag" >> $GITHUB_ENV
          echo "Nova versão gerada: $new_tag"

      - name: Criar nova tag
        run: |
          git tag ${{ env.new_tag }}
          git push origin ${{ env.new_tag }}

      - name: Criar release com notas automáticas
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh release create ${{ env.new_tag }} --title "Release ${{ env.new_tag }}" --generate-notes
